### ISSUE TITLE
Running the project as September 2023

### ISSUE THREAD

**Issue by j0t4** [thameera/saml-mock#1]
Advice on running this project nowadays...

Hi , trying to run this project  `npm i`  I get a lot of errors and warnings of deprecated packages....  It doesn't compile.

Then I tried  `npm i --force`  --> It  doesn't work. Run time error not found codemirror css files.

Found [here](https://discuss.codemirror.net/t/module-not-found-error/5510/8)  a solution -->

`npm i codemirror@version5 --force --save`  --> now  it works.

Thanks for this project, it helps me a lot understanding saml

**Comment by thameera** [comment]
@j0t4 Thanks for the report! I could repro the error. Will push a fix shortly.

**Comment by thameera** [comment]
Ended up moving to a @uiw/react-codemirror since react-codemirror2 is not being updated anymore. Upgraded Next, React and MUI versions as well so the project should build now without any errors. Let me know if you see any issues.

**Comment by j0t4** [comment]
Thanks for your attention and fast response, just a minor detail: 
in my setup , i use node version v16.15.1, and I had to remove `NODE_OPTIONS=--openssl-legacy-provider` in _package.json_  file in order to make "npm run dev" to work.

**Comment by thameera** [comment]
Thanks for that - I had forgotten about that flag. It's actually not needed anymore after the upgrades, so I've just removed it so this won't come up anymore.
