### ISSUE TITLE
`Issuer` is being signed instead of `Assertion`

### ISSUE THREAD

**Issue by spietras** [thameera/saml-mock#3]
Correct me if I'm wrong, but I believe that the `Issuer` element is being signed instead of the `Assertion` element, when we opt to sign the assertion.

One symptom of this behaviour I see is that the `Id="_0"` attribute is added to the `Issuer` element after signing.

I think this is because of the following code:

https://github.com/thameera/saml-mock/blob/a9fd5992df0a455ce9216f5d289f403110b24753/lib/signer.js#L8

Shouldn't it be like this instead?

```js
const ASSERTION_SIGNATURE_PATH = "//*[local-name(.)='Assertion']"
```

**Comment by thameera** [comment]
@spietras you are indeed right, just pushed a fix. Thanks for reporting!
