### ISSUE TITLE
Generated identifiers are not valid `ID` type

### ISSUE THREAD

**Issue by spietras** [thameera/saml-mock#4]
According to SAML 2.0 schemas, identifiers of various elements should be of type `ID`. For example in [the schema for `Assertion`](https://docs.oasis-open.org/security/saml/v2.0/saml-schema-assertion-2.0.xsd) the `ID` attribute is defined as:

```xml
<attribute name="ID" type="ID" use="required"/>
```

`ID` type is defined by [the XSD spec](https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#ID). Specifically it can't begin with a digit.

Because of that some SAML XML documents generated here fail schema validation, because the generated identifiers are numeric only.

The simplest solution to this would be to prepend something to the identifier. For example, an underscore: `_`. See also: https://stackoverflow.com/a/29798747.

**Comment by thameera** [comment]
@spietras Thank you for reporting, this is a great catch. Your suggestion on prefixing with an underscore is indeed a good workaround. I've pushed a fix, let me know if you see any issues.
